
[abstract]
== Abstract

MUDDI (Model for Underground Data Definition and Interchange) is a
representation of classes that serve as the basis that serve as the basis of
integration of datasets that utilize different information models in the
representation of underground objects.

MUDDI is meant to be comprehensive and provide sufficient level of detail to
address application use cases, including but not limited to the following:

* routine street excavations;
* emergency response;
* utility maintenance programs;
* large scale construction projects;
* disaster planning;
* disaster response; and
* Smart Cities programs.

MUDDI serves as an excellent basis for conformant and interchangeable logical
and physical implementations, such as GML (Geographic Markup Language) or SFS
(Simple Features SQL).

This OGC Standard provides the full set of MUDDI conceptual models and their
requirements.


== Preface

This OGC Standard provides the MUDDI conceptual models as described in UML.


== Submitters

All questions regarding this document should be directed to the editor or the
contributors:

[options="header"]
|===
| Name | Organization | Role

| Joshua Lieberman | OGC | Editor
| Carsten Roensdorf | Ordnance Survey Limited | Editor

|===
